
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home ///
/// Tue Dec 20 13:28:15 GMT 2016 ///

/// interface com.jh.SwiftHelloTest ///

public protocol SwiftHelloTest: JavaProtocol {

}

open class SwiftHelloTestForward: JNIObjectForward, SwiftHelloTest {

    private static var SwiftHelloTestJNIClass: jclass?

}


